name: Batch Course Downloader & Sync

on:
  workflow_dispatch:
    inputs:
      session_cookie:
        description: 'KodeKloud _secure-user-session cookie token'
        required: true
        type: string

jobs:
  download_and_sync:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        course_url:
          - 'https://learn.kodekloud.com/courses/kubernetes-challenges'
          - 'https://learn.kodekloud.com/courses/linux-challenges'
          - 'https://learn.kodekloud.com/courses/terraform-challenges'
          - 'https://learn.kodekloud.com/courses/cks-challenges'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-prompt-engineering-101'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-hashicorp-nomad'
          - 'https://learn.kodekloud.com/courses/aiops-foundations-intelligent-monitoring-with-prometheus-grafana'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-automated-remediation-with-python-for-aiops'
          - 'https://learn.kodekloud.com/courses/aiops-in-practice-logging-alerting-at-scale'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-applied-ml-for-aiops-anomaly-detection-forecasting'
          - 'https://learn.kodekloud.com/courses/mlops-for-aiops-build-track-and-orchestrate-ai-models-with-mlflow-kubeflow'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-advanced-aiops-distributed-tracing-and-rca-curriculum'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-core-dns-mastery'
          - 'https://learn.kodekloud.com/courses/learn-by-doing-rancher'
          - 'https://learn.kodekloud.com/courses/langsmith'
          - 'https://learn.kodekloud.com/courses/kgateway'
          - 'https://learn.kodekloud.com/courses/python-api-development-with-fastapi'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install KodeKloud Downloader
        run: pip install git+https://github.com/debakarr/kodekloud-downloader.git

      - name: Create Cookie File
        run: |
          printf ".kodekloud.com\tTRUE\t/\tTRUE\t0\tsession-cookie\t%s\n" "${{ inputs.session_cookie }}" > cookies.txt

      - name: Download Course
        run: python -m kodekloud_downloader.cli dl -o ./CourseDownload -c cookies.txt "${{ matrix.course_url }}"

      - name: Setup Rclone
        run: sudo curl https://rclone.org/install.sh | sudo bash

      - name: Sync to Cloud Drive
        run: |
          mkdir -p ~/.config/rclone
          cat << 'EOF' > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          rclone copy ./CourseDownload CloudDriveRemote:KodeKloud/ --progress
