name: Batch Course Downloader & Sync

on:
  workflow_dispatch:
    inputs:
      session_cookie:
        description: 'KodeKloud _secure-user-session cookie token'
        required: true
        type: string

jobs:
  download_and_sync:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        course_url:
          - 'https://learn.kodekloud.com/courses/aws-certified-ai-practitioner'
          - 'https://learn.kodekloud.com/courses/kubernetes-and-cloud-native-security-associate-kcsa'
          - 'https://learn.kodekloud.com/courses/az-204-developing-solutions-for-microsoft-azure'
          - 'https://learn.kodekloud.com/courses/az-400'
          - 'https://learn.kodekloud.com/courses/ai-900-microsoft-azure-ai-fundamental'
          - 'https://learn.kodekloud.com/courses/comptia-security-certification'
          - 'https://learn.kodekloud.com/courses/certified-cloud-native-platform-engineering-associate-cnpa'
          - 'https://learn.kodekloud.com/courses/certified-argo-project-associate-capa'
          - 'https://learn.kodekloud.com/courses/certified-backstage-associate-cba'
          - 'https://learn.kodekloud.com/courses/certified-jenkins-engineer'
          - 'https://learn.kodekloud.com/courses/aws-certified-sysops-administrator-associate'
          - 'https://learn.kodekloud.com/courses/cilium-certified-associate-cca'
          - 'https://learn.kodekloud.com/courses/finops-certified-practitioner'
          - 'https://learn.kodekloud.com/courses/ai-102-microsoft-certified-azure-ai-engineer-associate'
          - 'https://learn.kodekloud.com/courses/certified-kubernetes-security-specialist-cks'
          - 'https://learn.kodekloud.com/courses/aws-solutions-architect-associate-certification'
          - 'https://learn.kodekloud.com/courses/istio-certified-associate'
          - 'https://learn.kodekloud.com/courses/google-cloud-professional-data-engineer-certification'
          - 'https://learn.kodekloud.com/courses/dp-900-microsoft-azure-data-fundamentals'
          - 'https://learn.kodekloud.com/courses/kubernetes-and-cloud-native-associate-kcna'
          - 'https://learn.kodekloud.com/courses/ultimate-certified-kubernetes-application-developer-ckad-mock-exam-series'
          - 'https://learn.kodekloud.com/courses/az-305-microsoft-azure-solutions-architect-expert'
          - 'https://learn.kodekloud.com/courses/linux-professional-institute-lpic-1-exam-101'
          - 'https://learn.kodekloud.com/courses/prep-course-red-hat-certified-system-administrator-rhcsa'
          - 'https://learn.kodekloud.com/courses/hashicorp-certified-consul-associate-certification'
          - 'https://learn.kodekloud.com/courses/hashicorp-certified-vault-associate-certification'
          - 'https://learn.kodekloud.com/courses/hashicorp-certified-vault-operations-professional-2022'
          - 'https://learn.kodekloud.com/courses/linux-foundation-certified-system-administrator-lfcs'
          - 'https://learn.kodekloud.com/courses/pcap-python-certification-course'
          - 'https://learn.kodekloud.com/courses/docker-certified-associate-exam-course'
          - 'https://learn.kodekloud.com/courses/certified-kubernetes-application-developer-ckad'
          - 'https://learn.kodekloud.com/courses/microsoft-azure-security-technologies-az-500'
          - 'https://learn.kodekloud.com/courses/az900-microsoft-azure-fundamentals'
          - 'https://learn.kodekloud.com/courses/aws-certified-developer-associate'
          - 'https://learn.kodekloud.com/courses/demystifying-dns'
          - 'https://learn.kodekloud.com/courses/github-copilot-certification'
          - 'https://learn.kodekloud.com/courses/nvidia-generative-ai-llms-associate-certification'
          - 'https://learn.kodekloud.com/courses/gitops-certified-associate-cgoa'
          - 'https://learn.kodekloud.com/courses/az-700-designing-and-implementing-microsoft-azure-networking-solutions'
          - 'https://learn.kodekloud.com/courses/kyverno-certified-associate'
          - 'https://learn.kodekloud.com/courses/prep-course-opentelemetry-certified-associate-certification-otca'
          - 'https://learn.kodekloud.com/courses/ultimate-certified-kubernetes-security-specialist-cks-mock-exam-series'
          - 'https://learn.kodekloud.com/courses/hashicorp-certified-terraform-associate-004'
          - 'https://learn.kodekloud.com/courses/github-actions-certification'
          - 'https://learn.kodekloud.com/courses/prep-course-certified-cloud-native-platform-engineer-cnpe'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install KodeKloud Downloader
        run: pip install git+https://github.com/debakarr/kodekloud-downloader.git

      - name: Create Cookie File
        run: |
          printf ".kodekloud.com\tTRUE\t/\tTRUE\t0\tsession-cookie\t%s\n" "${{ inputs.session_cookie }}" > cookies.txt

      - name: Download Course
        run: python -m kodekloud_downloader.cli dl -o ./CourseDownload -c cookies.txt "${{ matrix.course_url }}"

      - name: Setup Rclone
        run: sudo curl https://rclone.org/install.sh | sudo bash

      - name: Sync to Cloud Drive
        run: |
          mkdir -p ~/.config/rclone
          cat << 'EOF' > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          rclone copy ./CourseDownload CloudDriveRemote:KodeKloud/ --progress